create schema mysql2

    create table mysql2.CUSTOMERS
    (
        id             int generated by default as identity primary key,
        name           varchar(50) not null,
        surname        varchar(50) not null,
        age            bigint       not null,
        phone_number   varchar(50),
        CHECK (Age > 0 AND Age < 100)
    );

--insert into mysql2.customers (name, surname, age, phone_number)
--    values ('John', 'Smiyh', 22, 99999999999);
--insert into mysql2.customers (name, surname, age, phone_number)
--values ('Tom', 'Cruse', 25, 88888888888);
--insert into mysql2.customers (name, surname, age, phone_number)
--values ('Angelina', 'Jolie', 47, 77777777777);
--insert into mysql2.customers (name, surname, age, phone_number)
--values ('Monica', 'Bellucci', 58, 66666666666);
--insert into mysql2.customers (name, surname, age, phone_number)
--values ('Elon', 'Musk', 51, 55555555555);
--insert into mysql2.customers (name, surname, age, phone_number)
--values ('Dmitry ', 'Nagiyev ', 51, 44444444444);