create table mysql2.ORDERS
(
    id           int generated by default as identity primary key,
    date         date        not null,
    customer_id  int REFERENCES mysql2.customers (id),
    product_name varchar(50) not null,
    amount       varchar(50)
);